apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.site.name | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.site.name | quote }}
  replicas: {{ .Values.site.replicas | default 1 }}
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: {{ .Values.site.name | quote }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: site
          image: {{ .Values.site.image | quote }}
          resources: {{ toYaml .Values.site.resources | nindent 12 }}
