apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.name | quote }}
spec:
  selector:
    app: {{ .Values.elasticsearch.name | quote }}
  ports:
  - name: "9200"
    port: 9200
  - name: "9300"
    port: 9300
