- name: HELM_ARGS
  valueIf:
    "ARGOCD_ENV_ENVIRONMENT == 'staging'": -f values.yaml  -f values.auto-updated.yaml  -f values.staging.yaml
    "ARGOCD_ENV_ENVIRONMENT == 'production'": -f values.yaml  -f values.auto-updated.yaml  -f values.production.yaml  -f values.auto-updated.production.yaml
