nfsServer: "172.16.0.9"

db:
  resources: {"requests": {"cpu": "25m", "memory": "512Mi"}, "limits": {"memory": "1Gi"}}
  nfsPath: "/srm/etl-production/db"
  backup:
    enabled: true

elasticsearch:
  resources: {"requests": {"cpu": "25m", "memory": "1Gi"}, "limits": {"memory": "2Gi"}}
  nfsPath: "/srm/etl-production/elasticsearch"
  secretName: "elasticsearch"
  ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
  enableBackups: true

kibana:
  resources: {"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"memory": "512Mi"}}

api:
  resources: {"requests": {"cpu": "25m", "memory": "128Mi"}, "limits": {"memory": "256Mi"}}
  ES_INDEX_NAME: "srm"
  ES_DATAPACKAGE: |
    https://srm.datacity.org.il/dataset/5423f041-47f3-4325-a116-8ae56c317d79/resource/d4dcb112-fcc9-4ea7-988d-e0819c4c79c3/download/datapackage.json
    https://srm.datacity.org.il/dataset/20a9ee57-1f33-4fc2-b620-875b27af27d4/resource/19e4cbb2-7383-4dc7-8c59-6711069ebcec/download/datapackage.json
    https://srm.datacity.org.il/dataset/812345ae-521e-4171-9a91-d66d0fcf03df/resource/c23e5c4f-078d-45b9-bc9c-356ed87c4028/download/datapackage.json
    https://srm.datacity.org.il/dataset/60337369-3d2c-49ba-beba-9f43abbd8f67/resource/0b46ddcd-ef4f-46c9-a9f8-257c0dd18260/download/datapackage.json
    https://srm.datacity.org.il/dataset/c5dd1e15-4be8-4eb8-b54e-28cab16fcd5e/resource/15112d71-3a67-42cb-bbbd-6fb316173e3b/download/datapackage.json
    https://srm.datacity.org.il/dataset/8aca960c-045c-447e-b823-21fbedd00651/resource/e46b3666-c1ac-4ce3-a430-f3580037fced/download/datapackage.json
    https://srm.datacity.org.il/dataset/4396eff1-e162-4a02-84e7-ae87e09f2cd1/resource/a298c07b-114d-4fd8-bfe4-a585b584e0f7/download/datapackage.json

minio:
  resources: {"requests": {"cpu": "25m", "memory": "128Mi"}, "limits": {"memory": "256Mi"}}
  nfsPath: "/srm/etl-production/minio"
  backup:
    enabled: true
    TARGET_BUCKET_PATH: "kolzchut-backups/srm-etl-minio"

etl:
  resources: {"requests": {"cpu": "247m", "memory": "1953Mi"}, "limits": {"memory": "4000Mi"}}
  EXTERNAL_ADDRESS: "https://srm-production-etl.whiletrue.industries"
  secretName: "etl"
  ckanHost: "https://srm.datacity.org.il"
  envName: "production"
  mapboxTilesetId: "srm-kolzchut.geo-data"
  mapboxTilesetName: "SRM Geo Data"

ingresses:
  - name: etl
    rules:
      - host: srm-production-etl.whiletrue.industries
        serviceName: etl
        servicePort: 5000
  - name: api
    rules:
      - host: srm-production-api.whiletrue.industries
        serviceName: api
        servicePort: 5000
  - name: kibana
    rules:
      - host: srm-production-kibana.whiletrue.industries
        serviceName: kibana
        servicePort: 5601
  - name: elasticsearch
    rules:
      - host: srm-production-elasticsearch.whiletrue.industries
        serviceName: elasticsearch
        servicePort: 9200

vertical_pod_autoscalers:
  - apiVersion: apps/v1
    kind: deployment
    name: api
  - apiVersion: apps/v1
    kind: deployment
    name: db
  - apiVersion: apps/v1
    kind: deployment
    name: elasticsearch
  - apiVersion: apps/v1
    kind: deployment
    name: etl
  - apiVersion: apps/v1
    kind: deployment
    name: kibana
  - apiVersion: apps/v1
    kind: deployment
    name: minio
