# nfsServer: ""

db:
  name: db
  image: ghcr.io/whiletrue-industries/srm-etl-db:623eb6ac56d5762b8d73acf6958946906378f429@sha256:2a448564a3d1c05f471fcb92f9489ac4cd6f8e9d77a0578265b99c4731d81603
  resources: {}
  # nfsPath: ""
  backup:
    enabled: false
    name: db-backup
    image: ghcr.io/whiletrue-industries/srm-etl-db:74f986e282fff4f39c831c22322c2b028be4f350@sha256:bf8ebbd5466d46557d8aba0468cc7f7f31d9fdd3a834f1add3a266fbe1960c8d
    # every Sunday 2:53
    schedule: "53 2 * * 0"
    resources:
      requests: {"cpu": "25m",  "memory": "200Mi"}
      limits: {"cpu": "165m", "memory": "400Mi"}

elasticsearch:
  name: elasticsearch
  image: ghcr.io/whiletrue-industries/srm-etl-elasticsearch:617261835d33baae54e244fedc8ef89f7a90a7dd@sha256:b8abc23ee75eb39aa831f3ca55f2d8db7dafb57500909cb817745a7e13a38666
  resources: {}
  # nfsPath: ""
  # secretName: "elasticsearch"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  enableBackups: false

kibana:
  name: kibana
  image: docker.elastic.co/kibana/kibana:7.13.3@sha256:4aef97e6d0ac46eec716337bff18ba4a7b4e101680039588b5729fc3f90bf730
  resources: {}

api:
  name: api
  image: ghcr.io/whiletrue-industries/srm-api:latest
  resources: {}
  ES_INDEX_NAME: "srm"
  ES_DATAPACKAGE: "https://next.obudget.org/datapackages/budgetkey/gov_decisions/datapackage.json"

# minio is only deployed if etl.S3_ENDPOINT is not defined
minio:
  name: minio
  image: minio/minio:edge@sha256:78b6513160ee72794698b808afbeff67b44b510d6d024e0728adc57d726b6c8b
  resources: {}
  backup:
    enabled: false
    name: minio-backup
    image: ghcr.io/whiletrue-industries/srm-devops-aws-s3-backup@sha256:fd44f4c0540dd68d0d154e39f5b70a7ed767414943881b7bab5298656cdfd964
    # every Sunday 2:13
    schedule: "13 2 * * 0"
    TARGET_BUCKET_PATH: ""
    resources:
      requests: { "cpu": "25m",  "memory": "200Mi" }
      limits: { "cpu": "165m", "memory": "400Mi" }

etl:
  name: etl
  image: ghcr.io/whiletrue-industries/srm-etl:latest
  resources: {}
  EXTERNAL_ADDRESS: "http://localhost:15000"
  secretName: "etl"
  # S3SecretName: "etl-s3"

ingresses: []
vertical_pod_autoscalers: []
