dataBackup:
  # every Sunday 2:33
  schedule: "33 2 * * 0"
  image: ghcr.io/whiletrue-industries/srm-devops-aws-s3-backup-ckan-data@sha256:8092ed950e217f57d3cca453f6800f7b68a88e8011ab1d2263c1ddde23d74a34
  resources:
    requests: { "cpu": "25m",  "memory": "300Mi" }
    limits: { "cpu": "165m", "memory": "600Mi" }

dbBackup:
  # every Sunday 2:46
  schedule: "46 2 * * 0"
  image: ghcr.io/whiletrue-industries/srm-devops-aws-s3-backup-ckan-db@sha256:4051312e8fc9260ef8bad9dfe37d73036860af05396e73e9bb0654556c209067
  resources:
    requests: { "cpu": "25m",  "memory": "300Mi" }
    limits: { "cpu": "165m", "memory": "600Mi" }

instanceBackup:
  # every Sunday 2:39
  schedule: "39 2 * * 0"
  image: ghcr.io/whiletrue-industries/srm-devops-aws-s3-backup-ckan-instance@sha256:20a46f6279ebdadc47e55e5cde9669f0ff3262503c3c2b45b65d08d7d81c6378
  resources:
    requests: { "cpu": "25m",  "memory": "300Mi" }
    limits: { "cpu": "165m", "memory": "600Mi" }
