site:
  resources: {"requests": {"cpu": "25m", "memory": "128Mi"}, "limits": {"memory": "256Mi"}}

ingresses:
  - name: site
    rules:
      - host: srm-production.whiletrue.industries
        serviceName: site
        servicePort: 4000
