apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: nginx-configuration
          configMap:
            name: nginx
      containers:
        - name: nginx
          image: {{ .Values.nginx.image | quote }}
          ports:
            - containerPort: 8080
          resources: {{ toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-configuration
              mountPath: /etc/nginx/conf.d
      terminationGracePeriodSeconds: 5
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
