apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image | quote }}
          ports:
            - containerPort: 6379
          resources: {{ toYaml .Values.redis.resources | nindent 12 }}
      terminationGracePeriodSeconds: 5
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
