apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: solr
          image: {{ .Values.solr.image | quote }}
          ports:
            - containerPort: 8983
          resources: {{ toYaml .Values.solr.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /opt/solr/server/solr/ckan/data/
      terminationGracePeriodSeconds: 5
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
