site:
  resources: {"requests": {"cpu": "25m", "memory": "128Mi"}, "limits": {"memory": "256Mi"}}

ingresses:
  - name: site
    rules:
      - host: srm-staging.whiletrue.industries
        serviceName: site
        servicePort: 4000

vertical_pod_autoscalers:
  - apiVersion: apps/v1
    kind: deployment
    name: site
