site:
  resources: {"requests": {"cpu": "25m", "memory": "128Mi"}, "limits": {"memory": "256Mi"}}

ingresses:
  - name: site
    rules:
      - host: kolsherut.org.il
        serviceName: site
        servicePort: 4000
  - name: site-www
    rules:
      - host: www.kolsherut.org.il
        serviceName: site
        servicePort: 4000
