site:
  replicas: 3
  resources: {"requests": {"cpu": "150m", "memory": "500Mi"}, "limits": {"memory": "1000Mi"}}

ingresses:
  - name: site
    rules:
      - host: kolsherut.org.il
        serviceName: site
        servicePort: 4000
  - name: site-www
    rules:
      - host: www.kolsherut.org.il
        serviceName: site
        servicePort: 4000
