name: ci
on:
  push:
    branches:
      - main
env:
  GITHUB_EVENT_BEFORE: ${{ github.event.before }}
  SRM_DEVOPS_DEPLOY_KEY: ${{ secrets.SRM_DEVOPS_DEPLOY_KEY }}
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  HELM_VERSION: "v3.7.0"
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
    - run: |
        curl -s https://raw.githubusercontent.com/OriHoch/uumpa-ci-toolbox/main/bin/github_actions_install.sh \
          | bash -s 22c1970adcd72930509ff5b8eabd52124a9e6866 OriHoch/uumpa-ci-toolbox &&\
        uci helm install --version "${HELM_VERSION}" --with-sudo &&\
        echo "${KUBECONFIG}" > .kubeconfig
        export KUBECONFIG="$(pwd)/.kubeconfig"
        uci git checkout \
          --github-repo-name whiletrue-industries/srm-devops \
          --branch-name main \
          --ssh-key "${SRM_DEVOPS_DEPLOY_KEY}" \
          --path srm-devops \
          --config-user-name srm-devops-ci &&\
        cd srm-devops &&\
        bin/ci.sh main "${GITHUB_EVENT_BEFORE}" "${GITHUB_SHA}"
